package com.converter.backend.dto.conversion;

import com.converter.backend.model.Conversion.InputFormat;
import com.converter.backend.model.Conversion.OutputFormat;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for creating a new conversion.
 * The 'aiResponse' is not included here as it is generated by the backend service.
 */
@Data
@NoArgsConstructor
public class ConversionCreateDto {

    @NotNull(message = "Output format cannot be null")
    private OutputFormat outputFormat;

    @NotNull(message = "Input format cannot be null")
    private InputFormat inputFormat;

    @NotBlank(message = "Prompt cannot be blank")
    private String prompt;
}